### ISSUE TITLE
Files referenced in README are not there

### ISSUE THREAD

**Issue by calicartel** [uber/chaperone#2]
Both scripts referenced under the <b>Start ChaperoneService section</b> are missing

<b>Start ChaperoneService Controller</b>
./ChaperoneDistribution/target/ChaperoneDistribution-pkg/bin/start-chaperone-controller.sh

<b>Start ChaperoneService Worker</b>
./ChaperoneDistribution/target/ChaperoneDistribution-pkg/bin/start-chaperone-worker.sh

**Comment by cloudXane** [comment]
hi @calicartel , I just tested those steps as in README. 

If 'mvn clean package -DskipTests' command succeeded with 
...
[INFO] Chaperone .......................................... SUCCESS [  5.072 s]
[INFO] ChaperoneServiceController ......................... SUCCESS [ 26.980 s]
[INFO] ChaperoneServiceWorker ............................. SUCCESS [ 23.985 s]
[INFO] ChaperoneClient .................................... SUCCESS [  2.974 s]
[INFO] ChaperoneCollector ................................. SUCCESS [  2.939 s]
[INFO] ChaperoneDistribution .............................. SUCCESS [  4.073 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS


Those scripts should be generated automatically

ls -l ./ChaperoneDistribution/target/ChaperoneDistribution-pkg/bin/
total 72
-rwxr-xr-x  1 xbli  staff  10636 Jan  6 10:20 start-chaperone-collector.sh
-rwxr-xr-x  1 xbli  staff  10518 Jan  6 10:20 start-chaperone-controller.sh
-rwxr-xr-x  1 xbli  staff  10905 Jan  6 10:20 start-chaperone-worker.sh
